site_name: Personal Website 
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


